import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Button from "@/components/atoms/Button";
import Link from "next/link";
import Layout from "@/components/organisms/Layout";

export default function Home() {
  const products = [1, 2, 3];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Layout
          childern={
            <div className="container-fluid px-4">
              <h1 className="mt-4">Users</h1>
              <ol className="breadcrumb mb-4">
                <li className="breadcrumb-item active">Users</li>
              </ol>
            </div>
          }
        ></Layout>
      </>
    </>
  );
}
